version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: erp
      POSTGRES_PASSWORD: QWERTY
      POSTGRES_DB: omg_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U erp -d omg_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    stdin_open: true
    tty: true
    container_name: server
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

volumes:
  pg_data: